### ISSUE TITLE
Pyregion require cython

### ISSUE THREAD

**Issue by flomertens** [conda-forge/pyregion-feedstock#4]
Issue: The pyregion package requires cython at runtime. When starting a script that use pyregion, I got the following error:

Traceback (most recent call last):
  File "/home/flo/Developpement/conda/envs/wise/bin/wise", line 4, in <module>
    __import__('pkg_resources').run_script('wise==0.4.7', 'wise')
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/flo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cython' distribution was not found and is required by pyregion

**Comment by cdeil** [comment]
I see: https://github.com/astropy/pyregion/blob/913af7ea4917855cb2e43d5086d1c8dd99c31363/setup.py#L95

Workaround: `conda install cython`

@bsipocz - what should we do?

Just list `cython` as dependency here in conda-forge?

Or cut a new pyregion release where `setup.py` is changed to no longer list Cython as required?
I guess this would require some work by you and me, to get CI to pass again for `pyregion` and to merge in the astropy-helpers updates? https://github.com/astropy/pyregion/pulls

**Comment by flomertens** [comment]
Thanks @cdeil for the feedback. I see that the issue is also that my script, which is an easy-install-script, is checking dependencies. Would any of you know how I could disable this dependency checking ?

**Comment by cdeil** [comment]
You're really using easy-install? That has been deprecated for many (close to 10?) years - you should use pip and/or conda. 

Probably `pip --no-deps` will do what you want?
https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-deps

**Comment by flomertens** [comment]
No what I meant is that I distribute a package (wise, https://anaconda.org/flomertens/wise) using conda. This package has a script which end up being install in bin/ as:

```
# EASY-INSTALL-SCRIPT: 'wise==0.4.7','wise'
__requires__ = 'wise==0.4.7'
__import__('pkg_resources').run_script('wise==0.4.7', 'wise')
```

This is when I call the script (so pkg_resources.run_script) that dependencies is checked, and I though maybe there is a way to not check dependencies at runtime. After all, as far as I know pyregion does not require cython during runtime.

**Comment by cdeil** [comment]
Correct, `pyregion` doesn't need Cython at runtime.

Note that pyregion is not an active project, I don't know if / when a patch release for this will go out.

So if you want to avoid this error for now, just `conda install cython` or list `cython` next to `pyregion` in your package requirements and it should work just fine.

**Comment by flomertens** [comment]
I'll leave this one to rest then.
